"""file -> task

Revision ID: a1566e4a8c3e
Revises: 8ab2830374dd
Create Date: 2022-11-19 22:52:37.092809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1566e4a8c3e'
down_revision = '8ab2830374dd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('task_id', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'files', 'tasks', ['task_id'], ['id'])
    op.add_column('tasks', sa.Column('name', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'name')
    op.drop_constraint(None, 'files', type_='foreignkey')
    op.drop_column('files', 'task_id')
    # ### end Alembic commands ###
